### ISSUE TITLE
Applied commit 9a101b5, "Could not find a package configuration file provided by "boost_timer"

### ISSUE THREAD

**Issue by fuxxociety** [Risca/OpenPHT#2]
Attempting to use your commit [9a101b5](https://github.com/Risca/OpenPHT/commit/9a101b505bbba03d4997aa03bca07764e2058fe5#diff-7c9bd03aff0cd236ef3a56abcfd5a630e95fc62a210e19c97250306b50e55f9b) to build OpenPHT on LibreELEC-9 sources. 

Boost-1.7 is built, and resides at
`~/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/timer.hpp
~/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/timer.hpp
~/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/config.hpp`

However, OpenPHT reports 
`BUILD      plexht (target)
    TOOLCHAIN      cmake (auto-detect)
-- Building OpenPHT, version: 1.9.0.0-4fd4daba
-- Building for target LINUX
-- Using FriBiDi: /home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libfribidi.a
-- Found Boost 1.70.0 at /home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS thread;system;timer
-- Found boost_headers 1.70.0 at /home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/cmake/boost_headers-1.70.0
-- Found boost_thread 1.70.0 at /home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/cmake/boost_thread-1.70.0
--   libboost_thread.a
-- Adding boost_thread dependencies: headers
-- Found boost_system 1.70.0 at /home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/cmake/boost_system-1.70.0
--   libboost_system.a
-- Adding boost_system dependencies: headers
CMake Error at /home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Could not find a package configuration file provided by "boost_timer"
  (requested version 1.70.0) with any of the following names:

    boost_timerConfig.cmake
    boost_timer-config.cmake

  Add the installation prefix of "boost_timer" to CMAKE_PREFIX_PATH or set
  "boost_timer_DIR" to a directory containing one of the above files.  If
  "boost_timer" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  /home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/toolchain/share/cmake-3.14/Modules/FindBoost.cmake:266 (find_package)
  plex/CMakeModules/PlatformConfigLINUX.cmake:73 (find_package)
  plex/CMakeModules/CMakeConfig.cmake:78 (include)
  CMakeLists.txt:55 (include)

-- Configuring incomplete, errors occurred!
See also "/home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/plexht-4fd4dabab/.x86_64-libreelec-linux-gnu/CMakeFiles/CMakeOutput.log".
See also "/home/fuxxy/RetroELEC/build.OpenPHT-Embedded-Generic.x86_64-9.80-devel/plexht-4fd4dabab/.x86_64-libreelec-linux-gnu/CMakeFiles/CMakeError.log".
FAILURE: scripts/install plexht has failed!
`

**Comment by fuxxociety** [comment]
In older versions of LibreELEC, OpenELEC, and (in my case) RetroELEC that are forked from the LibreELEC 9.x sources, boost-timer is not built when compiling Boost>=1.70.0 . Make sure the build environment has actually built 'boost-timer'. 

https://github.com/fuxxociety/OpenPHT-Embedded-le9/commit/931ef4d563517540b945125d8edc16fa55c6bfb1

**Comment by Risca** [comment]
Thanks for the hint! :D
